export const categories = [
  'Food',
  'Travel',
  'Shopping',
  'Bills',
  'Entertainment',
  'Health',
  'Education',
  'Transport',
  'Rent',
  'Insurance',
  'Subscriptions',
  'Personal Care',
  'Fitness',
  'Electronics',
  'Misc',
];